### PR TITLE
remove two non consistent squares

### PR DESCRIPTION
**Pull request by rjanvier**
I believe these thresholds were squared by mistake. While I agree we could maybe raise the angular threshold, the squared residual error is far too permissive.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Related: #1373

**Comment by rjanvier** [comment]
Yes I agree it's related to squaring thresholds, but here it's maybe more obvious than in the case of loss width.

**Comment by NikolausDemmel** [comment]
Have you checked if the respective functions maybe expect squared thresholds?

**Comment by rjanvier** [comment]
I know what I'm doing here ;). And an angle is unlikely to be squared.

**Comment by pmoulon** [comment]
In fact here, the square was made on purpose.
Since here, we have an initial reconstruction (the 3D seed), I want to give more chance for the first round of resection to add new camera... Perhaps this is not a good idea. We can try this experimentally and see what is the best option (Conservative, or permissive and then conservative)...

**Pull request closed without merging**
