### PR TITLE
[software/sfm] Remove unused import from python scripts

### PR DESCRIPTION
**Pull request by mardy**

### CODE REVIEW

**Comment by rperrot** [comment]
That's for this PR. I think this helps running on python 2 AND python 3.

**Comment by mardy** [comment]
Indeed. For the record, I'm using python3 to run the scripts.

**Comment by pmoulon** [comment]
Thank you @mardy. I will merge it to the develop branch in order to have this update in the next coming release!

**Comment by pmoulon** [comment]
Thank you
Merged by https://github.com/openMVG/openMVG/commit/c95ee7e69d9a3ea291f206deab3b9e6da5a41f0d

**Pull request closed without merging**
