### PR TITLE
Update OpenMVS.rst

### PR DESCRIPTION
**Pull request by PengPPSUC**

### CODE REVIEW

**Comment by pmoulon** [comment]
Can you provide a description for your PR?

- OpenMVG2OpenMVS already exported the undistorted images so I did not catch why you add this command line to this documentation.

**Comment by PengPPSUC** [comment]
I see that the explanation for "-d" is "undistorted images path", that is, one of its inputs should be undistorted images, but in OpenMVG, "openMVG_main_ExportUndistortedImages" is only available as Optional further processing. So I would like to remind you to do "openMVG_main_ExportUndistortedImages" first,and then do the OpenMVG_main_openMVG2openMVS.

**Comment by PengPPSUC** [comment]
In main_openMVG2openMVS.cpp,I saw that the explanation for "-d" is "undistorted images path", that is, one of its inputs should be undistorted images, but in OpenMVG, "openMVG_main_ExportUndistortedImages" is only available as Optional further processing. So I would like to remind you to do "openMVG_main_ExportUndistortedImages" first,and then do the OpenMVG_main_openMVG2openMVS

**Comment by PengPPSUC** [comment]
In main_openMVG2openMVS.cpp,I saw that the explanation for "-d" is "undistorted images path", that is, one of its inputs should be undistorted images, but in OpenMVG, "openMVG_main_ExportUndistortedImages" is only available as Optional further processing. So I would like to remind you to do "openMVG_main_ExportUndistortedImages" first,and then do the OpenMVG_main_openMVG2openMVS.



At 2017-05-21 23:07:06, "Pierre Moulon" <notifications@github.com> wrote:


Can you provide a description for your PR?

OpenMVG2OpenMVS already exported the undistorted images so I did not catch why you add this command line to this documentation.

**Comment by pmoulon** [comment]
`-d` option is a export directory and not an input directory.
`main_openMVG2openMVS` will export the undistorted image for you.

**Comment by PengPPSUC** [comment]
oh，I got it，thank you for your patience！





At 2017-05-22 12:59:24, "Pierre Moulon" <notifications@github.com> wrote:


-d option is a export directory and not an input directory.
main_openMVG2openMVS will export the undistorted image for you.

**Pull request closed without merging**
