### PR TITLE
Merging LATCH and Deep Descriptor repository

### PR DESCRIPTION
**Pull request by mdaiter**
For some time, @pmoulon and I have been discussing our potential merge of our repos into one unified, stable base. My repository adds multiple new features, such as LATCH descriptor generation, Deep Descriptor generation and GPU-based matching to the repository. I'd like to open this PR as a way to instantiate the refining and (hopefully) eventual merge of these repositories, as I believe this should aid, accelerate and broaden the endeavours of many who use openMVG.

### CODE REVIEW

**Comment by mdaiter** [comment]
As an update: I'll begin personally merging the `master` branch from openMVG. However, I'd appreciate any feedback regarding refinements in the codebase!
One particular section that caught my eye had been the `Impl` mechanism used in the `Cascade_Matcher` to allow for multiple types of descriptors to immediately be used. This may easily cut down the (big) case statement located in the `GPU_Matcher_All_In_Memory` and clarify the functionality of the `GPU_Matcher_All_In_Memory`.

**Comment by donlk** [comment]
Merging to master would probably not be a good idea, as its merged mainly when a new release is pushed. I suggest @pmoulon to create a new branch for this based on develop.

**Comment by mdaiter** [comment]
"These conflicts are too complex to resolve in the web editor" oh boy!

**Comment by pmoulon** [comment]
Hi @mdaiter 

Thanks a lot for this PR.
Really appreciate it.

1. Please note that PR must be pushed to develop (this is the place were we are working on next features development).

2. I would like to introduce change smoothly. So perhaps it would be better to work on introducing new content incrementally and be sure that the integration will be smooth for the OpenMVG project and for the community.
I mean we certainly need some new unit test and the CUDA backend compilation must also be tested on the Continuous Integration side (travis).

3. So perhaps you can list there all the additions you have and then we can prioritize in order to add things feature by feature.

4. Additionally I love to have CPU/GPU backend:
- in order to let people compare the CPU/GPU implementation
- in order to let people play with the code even if they don't have a GPU (server farm...).

Regarding the `GPU_Matcher_All_In_Memory` I did not catch your point (please look to the develop branch) and elaborate.

Thanks you very much for your understand of the various points.

Let's continue the discussion and I'm inpatient to work on all of this with you and the community!

**Comment by mdaiter** [comment]
Hey @pmoulon ,
1. Alright, I'll attempt to merge onto develop!
2. Agreed, I don't think we should dump all of these commits at once to the repo. I'll attempt to continually integrate across multiple commits.
3. Sure. I'll do that here:

- LATCH descriptor (GPU backend)
- Deep descriptor support (Torch loader that can use CPU/GPU/OpenCL)
- GPU-based matcher (L2 and Hamming support)
- Minor touchups/optimizations (regarding some variables appended with `const`, `__attributes__` added to headers, etc.)

I can't wait as well! I'm going on vacation for a month starting Friday. Afterwards, I should be relaxed and ready to start this integration.

**Comment by pmoulon** [comment]
What about doing stuff in this order:

1. use on your side a new branch starting for the actual develop
2. Integrate slowly all the change in order to have a clean history and a per feature PR
3. Perform the change in this order (by increasing difficulty):
-  Minor touchups/optimizations (regarding some variables appended with const)
    - note that __attributes__ is GCC compatible only. OpenMVG is Visual Studio compiler compatible ;-)

- LATCH descriptor (GPU backend)
  - in the meantime I can work on the CPU backend in order to offer to the community the best of the two world 😄 

- GPU-based matcher (L2 and Hamming support)
  - Can you tell us if they are OpenCV dependent?
 
- Deep descriptor support (Torch loader that can use CPU/GPU/OpenCL)
  - postponed to the end. Since this one involves more third-party ...

**Comment by pmoulon** [comment]
Enjoys your day off 🎿  🏖 .
I cannot wait to work with a fully charged @mdaiter 😄 

I will see if during your month off I will have time to work on the LATCH CPU backend.

**Comment by rperrot** [comment]
I totally agree with Pierre. 

This is a huge work and lots of things are really interesting and may have a large impact on some users (I'm particularly impatient to test LATCH descriptor). 

But merging it as a whole seems really difficult and for history reason a PR may be for one feature at a time (this also helps finding regression bugs if any exist : bugs are more localized, regressions tests are fewer and fix are faster).

**Comment by pmoulon** [comment]
Since we are working on develop_koral branch regarding some of those features I'm closing this issue.

**Pull request closed without merging**
