### PR TITLE
[continuous integration] added support for gcc 9

### PR DESCRIPTION
**Pull request by gandrademachine**
Needed for latest Ubuntu 19.10

### CODE REVIEW

**Comment by pmoulon** [comment]
I notice also that we don't have GCC8 tested.
Do you want to add it too?

**Comment by GabrielMachine** [comment]
Sure I can

**Comment by pmoulon** [comment]
You can add a commit to your branch and it will show up here directly.

**Comment by GabrielMachine** [comment]
I sent the PR with the changes. waiting for checks.

**Comment by GabrielMachine** [comment]
The PR is passing with gcc-9 but fails with gcc-8 in a single test 58GLOBAL_SFM_RotationAveragingL2_TranslationAveragingL1_Test. I will first rebase the PR on develop branch, to see if this has been fixed. I will also file a separate issue regarding gcc8

**Comment by pmoulon** [comment]
Thx. Merged https://github.com/openMVG/openMVG/commit/160643be515007580086650f2ae7f1a42d32e9fb

**Pull request closed without merging**
