### PR TITLE
[BUILD] Fix compilation on GCC + Mac OS #1580

### PR DESCRIPTION
**Pull request by rfabbri**
There was a compile error with GCC 5 under Mac, due to a lacking
explicit instantiation for size_t.
This commit proposes a fix to #1580. GCC + Mac is not on Travis.

### CODE REVIEW

**Comment by pmoulon** [comment]
Would be nice to add `GCC + Mac` on Travis in the same PR to ensure we have all the compilation passing.

**Comment by rfabbri** [comment]
Do I just add the modified `OpenMVG/.travis.yml` to the PR ? Or is there better a GUI/github way?

**Comment by pmoulon** [comment]
You can commit in the same branch `rfabbri:gcc-mac-fix` and this PR will be automatically updated with your additional commit.

**Comment by pmoulon** [comment]
Any luck about adding `GCC + Mac` on travis CI?

**Comment by rfabbri** [comment]
I have more time to work on this now, will do.

**Comment by pmoulon** [comment]
Thank you!

**Comment by rfabbri** [comment]
My `.travis.yml` proposal is final. The build matrix now lists these builds, and I have also added a 'xcode11' build (without GCC) in the process, I think it is useful for current systems.
 
I have decided to keep the GCC Mac OS builds under `allow_failures` for now. The reason is that they are currently failing for silly reasons - g++ is currently including a clang "standard" C header that misses clang-specific definitions just introduced by Apple. See more about this and some work arounds here: https://github.com/Homebrew/homebrew-core/issues/40676

Basically, the way you can work-around while we wait for Apple to fix this is to reorder certain standard headers. The errors we are getting now start with: 

```
/usr/local/bin/g++-5  -DOPENMVG_USE_OPENMP -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/.  -I/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/./CoinUtils/src -I/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/./Osi/src/Osi -I/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/./Clp/src -I/Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/./Clp/src/OsiClp -march=broadwell -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mfma -mbmi2 -mavx2 -mno-sse4a -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-avx -mno-avx2 -fopenmp -fPIC -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14   -O3 -Wall -ffast-math -std=gnu++11 -o CMakeFiles/lib_CoinUtils.dir/CoinBuild.cpp.o -c /Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinBuild.cpp
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:110:0,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:66,
                 from /usr/local/Cellar/gcc@5/5.5.0_3/include/c++/5.5.0/cstdlib:72,
                 from /Users/rfabbri/cprg/vxlprg/lemsvpe/openMVG/src/dependencies/osi_clp/CoinUtils/src/CoinBuild.cpp:7:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/resource.h:443:34: error: expected initializer before '__OSX_AVAILABLE_STARTING'
 int     getiopolicy_np(int, int) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);

```
I have a C++11 project with trifocal geometry code that I am trying to contribute to OpenMVG, and I added a `.travis.yml` to it based on the OpenMVG `.travis.yml`. My code builds no problem with GCC on Mac OS: https://travis-ci.org/rfabbri/minus
If I put an `#include <cstdlib.h>` in the beginning of any C++ file, I get the same errors as I get with OpenMVG
I am interested in GCC because my solver is so fast for certain optimizations I am using with GCC5.

So, I propose we use the .travis.yml from this pull request and monitor the Mac OS + GCC platform.
Apple is likely to provide a minor fix, which will make these builds green, so we need to watch them without affecting the entire build status.

**Comment by rfabbri** [comment]
This `.travis.yml` should now be ready. Previous build for 2154366 broke due to a log/connection error within windows build server, not our fault.

**Comment by pmoulon** [comment]
Fixed by https://github.com/openMVG/openMVG/commit/a81c9f95b6d36ac2040aef29c65aa8ae3816d651
Thx you @rfabbri :tada:

**Pull request closed without merging**
