### PR TITLE
Add sensor width definition for the Sony A7II.

### PR DESCRIPTION
**Pull request by xorgy**

### CODE REVIEW

**Comment by pmoulon** [comment]
Did you try to add also `Sony ILCE-7M2;35.8`?

**Comment by xorgy** [comment]
@pmoulon Ahh, I wasn't aware that that was the format. It looked weird to me. Is that first token simply ignored?

**Comment by pmoulon** [comment]
It depends of the camera model. Some camera include the `Brand` and some other does not.

**Comment by xorgy** [comment]
@pmoulon Yeah, in this case the EXIF data just says ILCE-7M2.

**Comment by pmoulon** [comment]
Thx, Merged by https://github.com/openMVG/openMVG/commit/0312259d9795368140936cfc527f79bb39ccd111

**Pull request closed without merging**
