### PR TITLE
Switch to JSON for file formats

### PR DESCRIPTION
**Pull request by Meekohi**
See issue #42. Adds JsonBox to the project for reading/writing JSON files (trust me, I tried several libraries and this is the one you want). So far only switched lists.txt to imageParams.json, but more to follow.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Any plan to merge that?

**Comment by simogasp** [comment]
+1

**Comment by pmoulon** [comment]
Integrate directly this input format in the 0.8 is a bit dangerous, but will could definitively consider it as an I/O module for the 0.9.

I would prefer first add a binary to export some data in JSON for the 0.8 and smoothly go to a full JSON module I/O for the 0.9.

We could for example write first a main_openMVG2JSON that would convert an openMVG SfM scene in a set of JSON files.

What do you think about that?

**Comment by fabiencastan** [comment]
I would prefer to avoid this intermediate step that will create more confusion.
Most of those files are internal files, so it should not have a big impact on users. It should just be clear in the release note.

**Pull request closed without merging**
