### PR TITLE
Sfm Data Colorization

### PR DESCRIPTION
**Pull request by SBCV**
This is a PR to provide the sfm colorize functionally for different executables (main_openMVG2Colmap, main_openMVG2NVM)

At the moment the line (line 100 in sfm_data_colorization.cpp)
`const bool b_rgb_image = ReadImage(sView_filename.c_str(), &image_rgb);`

causes the following error message 

`../../Linux-x86_64-Release/libopenMVG_sfm.a(sfm_data_colorization.cpp.o): In function `openMVG::sfm::ColorizeTracks(openMVG::sfm::SfM_Data const&, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >&, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >&)':
sfm_data_colorization.cpp:(.text+0x979): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
sfm_data_colorization.cpp:(.text+0xda0): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
sfm_data_colorization.cpp:(.text+0x1057): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
sfm_data_colorization.cpp:(.text+0x1548): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
../../Linux-x86_64-Release/libopenMVG_sfm.a(sfm_data_colorization.cpp.o): In function `int openMVG::image::ReadImage<unsigned char>(char const*, openMVG::image::Image<unsigned char>*)':
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0x57): undefined reference to `openMVG::image::ReadImage(char const*, std::vector<unsigned char, std::allocator<unsigned char> >*, int*, int*, int*)'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0xc9): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgba<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0x162): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgba<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0x21c): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0x2b5): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0x67f): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgb<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageIhEEiPKcPNS0_5ImageIT_EE]+0x86e): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgba<unsigned char> >'
../../Linux-x86_64-Release/libopenMVG_sfm.a(sfm_data_colorization.cpp.o): In function `int openMVG::image::ReadImage<openMVG::image::Rgb<unsigned char> >(char const*, openMVG::image::Image<openMVG::image::Rgb<unsigned char> >*)':
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE]+0x57): undefined reference to `openMVG::image::ReadImage(char const*, std::vector<unsigned char, std::allocator<unsigned char> >*, int*, int*, int*)'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE]+0xb6): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgba<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE]+0x14f): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgba<unsigned char> >'
sfm_data_colorization.cpp:(.text._ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE[_ZN7openMVG5image9ReadImageINS0_3RgbIhEEEEiPKcPNS0_5ImageIT_EE]+0x51e): undefined reference to `vtable for openMVG::image::Image<openMVG::image::Rgba<unsigned char> >'
collect2: error: ld returned 1 exit status
make[2]: *** [Linux-x86_64-Release/openMVG_main_ComputeSfM_DataColor] Error 1
make[1]: *** [software/SfM/CMakeFiles/openMVG_main_ComputeSfM_DataColor.dir/all] Error 2
make: *** [all] Error 2`

With 
`const bool b_rgb_image = true; // ReadImage(sView_filename.c_str(), &image_rgb); `
the PR compiles and links correctly

I'm pretty sure this is caused by the template used by openMVG::image::Image. 
Unfortunately my c++ template experience is quite limited ...
Any ideas / suggestions?

### CODE REVIEW

**Comment by pmoulon** [comment]
Thx I will take a look in the coming days.

**Comment by SBCV** [comment]
Thank you!

**Comment by pmoulon** [comment]
Thx @SBCV.

I merged your changes here: https://github.com/openMVG/openMVG/commit/6fcc3e85add18e6e9ca1e53effa48a4feb27efab

I think the undefined function by adding the missing linked library: https://github.com/openMVG/openMVG/commit/5b2c7903f57bc401513ee7b221a7db976bb101e7#diff-c4e7d384906636d63dabada049b55348R34.

Feel free to use this for your other PR ;-)

**Comment by SBCV** [comment]
Ah okay, that makes sense! I'll update the other PR, accordingly!

**Pull request closed without merging**
