### PR TITLE
modified some places to make it able to compile the software under "ui" folder

### PR DESCRIPTION
**Pull request by chaoer**
I wrongly started my work on the master branch last time, 
and now this is start from the develop branch.
Hope this can be useful for someone.
---------------------------------------------------------------------------------------------------------

1. modify the "src\software\CMakeList.txt" in line 13-17
_comment:_
**change to find Qt5**
In " ui\SfM\adjacency_matrix_viewer ", it uses Qt5.
In " ui\SfM\control_points_registration ", it uses Qt4.

In consideration of that we usually use Qt5 now, thus I change this to find Qt5.

--------------------------------------------------------------------------------------------------------------

2. modify the "src\software\ui\SfM\adjacency_matrix_viewer\matchingpairgraphicsview.h" in line 12
_comment:_
**comment the define of class MainFrame**
When I compile this project (adjacency_matrix_viewer) with Qt5 using VS2015 X64, the IDE reports LINK ERROR 2019 unresolved external symbol (the construct of class MatchingPairGraphicsView, specifically).

Thus I comment the define of class, and add the include sentence. Then the error disappears.

---------------------------------------------------------------------------------------------------------------
3. modify the "src\software\ui\SfM\control_points_registration\CMakeLists.txt"
_comment:_
**modify the CMakeList.txt**
for two reasons:
the older one use Qt4;
the older one did not work when I compile it with Qt4.

--------------------------------------------------------------------------------------------------------------
4. modify the "src\software\ui\SfM\control_points_registration\mainLayout.hpp"
                      "src\software\ui\SfM\control_points_registration\mainLayout.cpp"
                      "src\software\ui\SfM\control_points_registration\GraphicsMainWindow.cpp"
_comment:_
**add includes**
if without these includes, the IDE (vs2015 x64) reports errors.

### CODE REVIEW

**Comment by chaoer** [comment]
Uh. I give up. 
I get those errors: from the machine on Travis when doing continuous integration:

CMake Error at software/CMakeLists.txt:13 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:
    Qt5Config.cmake
    qt5-config.cmake
  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!

**Comment by pmoulon** [comment]
Build fail since Qt5 is not installed in the continuous integration machine.

**Comment by pmoulon** [comment]
I made a fast test here on the branch `develop_gui_travis`:

As you see QT5 is now detected:
https://travis-ci.org/openMVG/openMVG/jobs/234560426#L628

I made the following changes to your PR:
- add qt5 package setup in the travis script
- add a CMAKE variable `OpenMVG_BUILD_GUI_SOFTWARES` in order to activate or not the GUI build.
  - QT5 GUI applications are only optional. 

Depite QT5 is detected, we have build errors:
- https://travis-ci.org/openMVG/openMVG/jobs/234560426#L1600
Any ideas?

PS: this link was useful http://philipbradley.net/capybara-react-qt5-and-travis-ci/

**Comment by chaoer** [comment]
@pmoulon  Sorry for reply too late.

I checked the [https://travis-ci.org/openMVG/openMVG/jobs/234560426#L1600](url). I think information in the line 1599 maybe useful. 

I will try to use the following code (do a forced type conversion), and if it works i will tell you as soon as possible.
`m_brown_act = new QAction( QObject("Brown (3R-2T)") );`

**Comment by chaoer** [comment]
@pmoulon Oops.  you have already modified it. 

 Is it works now?

**Comment by pmoulon** [comment]
@chaoer I try another way to create a QAction but it is still not ok:
https://travis-ci.org/openMVG/openMVG/jobs/234697873#L1461

**Comment by pmoulon** [comment]
@rperrot Helped to find a fix for QAction.
I'm currently looking to the behavior on `QByteArray::fromStdString(svg_string)`. I'm actually trying `QString::fromStdString(svg_string)`

**Comment by pmoulon** [comment]
@chaoer, @rperrot 
The build on the continuous integration is now OK for the QT applications:
- https://travis-ci.org/openMVG/openMVG/jobs/235074717

I will make a clean branch with your commit and my modification and merge it to develop soon.

**Comment by chaoer** [comment]
@pmoulon  Thanks for your work.

**Comment by pmoulon** [comment]
Merged by https://github.com/openMVG/openMVG/commit/57a6d5f9380b29370e2e2b0b19aced13ff0d5d10 and fixed by https://github.com/openMVG/openMVG/commit/4553f82cbe92b20cce5dcc4681339d43f5643c7a.

Thanks @chaoer 
Looking forward to see another PRs :+1:

**Pull request closed without merging**
