### PR TITLE
Add an function spliting matches.x.y file into matches_COMPONENTID_SIZE.X.Y and a test main function

### PR DESCRIPTION
**Pull request by whuaegeanse**
make a PR to replace the former PR #1061

### CODE REVIEW

**Comment by pmoulon** [comment]
Thx, Travis continuous integration is ok.
For the moment we don't care about the VStudio continuous integration (they made some change on AppVeyor and the script is not working anylonger 😢 )

I will review it and merge it soon.

**Comment by whuaegeanse** [comment]
Hi @pmoulon ，hope this PR will be merged into openMVG 1.3 as mentioned in #1150.

**Comment by pmoulon** [comment]
Sure, I added the milestone flag as a reminder ;-)

**Comment by pmoulon** [comment]
@whuaegeanse Thank you for your contribution and updated PR.
The code is now merged!
Looking forward your next PR!

**Comment by whuaegeanse** [comment]
It's my pleasure.

**Pull request merged**
