### PR TITLE
fix broken build and license link in README

### PR DESCRIPTION
**Pull request by n3a9**

### CODE REVIEW

**Comment by pmoulon** [comment]
Thank you.

- The problem for the BUILD.md (thanks to another PR in the develop branch)
- I will fix the link for the LICENSE.

The policy for update is first to propose changes to develop and then when a release is pushed it is merged to master.

**Comment by n3a9** [comment]
Ah, sorry about that. Saw the broken links and just thought i should make PR

**Comment by pmoulon** [comment]
No problem. I appreciate the PR since you found a new problem about the licence link ;-)

**Comment by pmoulon** [comment]
Thx. Fixed by https://github.com/openMVG/openMVG/commit/3c45671a4eb19a9c401a257277f284b988de901b

Looking forward any new PR in the future ;-)

**Comment by pmoulon** [comment]
Note: The fix will be pushed to master for the next release.

**Comment by n3a9** [comment]
🎉

**Pull request closed without merging**
