### PR TITLE
Less work for image feature tracking

### PR DESCRIPTION
**Pull request by greenlet**
FYI. There's no major improvements, just less work and less code as flat_pair_map could be removed

### CODE REVIEW

**Comment by pmoulon** [comment]
Did you compare speed (before/after)?
i would assume that inserting in a map is slower than inserting in a vector and sorting.

**Comment by greenlet** [comment]
> Did you compare speed (before/after)?
> i would assume that inserting in a map is slower than inserting in a vector and sorting.

I haven't made measurements. But inserting in a map has the same complexity as inserting into set
```std::set<indexedFeaturePair> allFeatures;```
`std::map` and `std::set` are both sorted structures

**Comment by pmoulon** [comment]
Let's try to bench on many scenes and then consider to merge depending on the timing results.

You can add a timer here on this binary and quit early to benchmark (Running X times in a loop could also help to have more accurate timing) https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/export/main_exportTracks.cpp#L114

**Comment by pmoulon** [comment]
The key for speed is to avoid repetitive memory allocation, using the flat_map allow to have already the memory and insertion gonna be quick. Using a set will guarantee quick insertion but will make repetitive memory allocation.

Let's benchmark it and see ;-)

**Comment by greenlet** [comment]
Ok. I can do benchmark later

**Pull request closed without merging**
