### PR TITLE
closed(#1618)

### PR DESCRIPTION
**Pull request by GabrielMachine**

### CODE REVIEW

**Comment by GabrielMachine** [comment]
I forgot to mention that this pull request closes the following issue:https://github.com/openMVG/openMVG/issues/1618

**Comment by pmoulon** [comment]
Actually you see that the CI (Continuous Integration) is failing, so build is not working. See above `The Travis CI build failed`.
Did you try to build and run unit tests on your side before pushing a PR?

**Comment by pmoulon** [comment]
If you want to remove FRIEND, you have to use member function and so you have to change some code:

```
  bool operator==(const IndMatch& m) const {
    return (this->i_ == m.i_ && this->j_ == m.j_);
  }

  bool operator!=(const IndMatch& m) const {
    return !(*this == m);
  }

  // Lexicographical ordering of matches. Used to remove duplicates
  bool operator<(const IndMatch& m) const {
    return (this->i_ < m.i_ || (this->i_ == m.i_ && this->j_ < m.j_));
  }

**Comment by GabrielMachine** [comment]
Ok, I'll make these changes in file and test everything that have to be tested.

**Comment by pmoulon** [comment]
If you are gonna fix this because we decide that friend function are not appropriate to have we should consider to fix all of them. See this https://github.com/openMVG/openMVG/search?utf8=%E2%9C%93&q=%22friend+bool%22&type= We have friend operator in various classes.  Personally I don't see this as an issue since it allow to use some of those operator as function operators.

But if we are gonna consider fixing it it here I want a uniform decision across the project.

@rperrot any comment on friend operator or member function?

**Comment by GabrielMachine** [comment]
closing to try another solution

**Comment by rperrot** [comment]
Hi, 

regarding friend keyword, it has never been an issue for operators (Core guidelines agrees with that). 

There are some issues with friend but it's not the case here:
- Long friend chip (accès to friend of a friend of a friend ...)
- friendchip that will break encapsulation too much (though it's not true because friend is only allowed if your class accept it) ;

The only thing that we may be prudent is :
- Automatic conversion may break behavior, with member function one of the operator can't be implicitly converted (on the first operand), with friend function it can happened. 

For operator== it we don't use class inheritance I think it's ok. But if inheritance and genericity occurs, we may prefer a function like "bool equal()" to make sure we don't do anything weird.

**Comment by pmoulon** [comment]
@GabrielMachine Let's let the code as it is. I don't think we have a serious issue here.
Thank you for your feedback. Appreciated. It is always good to have a second look on the designed API and check we made the things in the right way.

Feel free to discuss with us if you want to contribute and help the project by writing here openmvg-team[AT]googlegroups.com

**Pull request closed without merging**
