### PR TITLE
Develop koral merge

### PR DESCRIPTION
**Pull request by mdaiter**
Let's get these changes integrated to stay up-to-date with the base.

### CODE REVIEW

**Comment by mdaiter** [comment]
@pmoulon ?

**Comment by pmoulon** [comment]
Yep, will do the review soon.

**Comment by pmoulon** [comment]
Hi @mdaiter I merge the PR and made some modification.
Did not check if it compiles or not.
Next step will be:
- [ ] to configure an additional line in the travis build matrix in order to test the CUDA compilation back end (@mdaiter)
- [ ] to implement a pure KORAL CPU back end (@pmoulon)

- implement a hamming GPU matching backend (optimized for LATCH descriptor)

**Comment by mdaiter** [comment]
@pmoulon I think Kareem already made a CUDA Hamming GPU matching backend optimised for LATCH! Lemme see if I can get this integrated :D

**Comment by pmoulon** [comment]
I can help you on that for the CPU backend (MIH).

**Comment by mdaiter** [comment]
@pmoulon I think @komrad36 also has that covered ;)

**Pull request merged**
