### PR TITLE
index conflict with input k

### PR DESCRIPTION
**Pull request by gaoshuai**

### CODE REVIEW

**Comment by pmoulon** [comment]
This pull request **fixes 1 alert** when merging 2ba3b261a78b713becf8448d0fa03e3440d600d7 into 835f1e585377a55d4143548fa9181438f5d23889 - [view on LGTM.com](https://lgtm.com/projects/g/openMVG/openMVG/rev/pr-e186ae570b2878a50465a09dbb721ed06f13832b)

**fixed alerts:**

* 1 for Declaration hides parameter

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by gaoshuai** [comment]
I also think the k parameter should be added to the function below:
makelogcombi_n(n, vec_logc_n, vec_log10);

**Comment by pmoulon** [comment]
Thank you for the fix.
Regarding https://github.com/openMVG/openMVG/pull/1508#issuecomment-484964439, there is two different combinations to generate, the k and n parameters are correct.

**Comment by pmoulon** [comment]
This pull request **fixes 1 alert** when merging 2ba3b261a78b713becf8448d0fa03e3440d600d7 into a920aa56e5673d3300206ba15fd7cd74d837fcef - [view on LGTM.com](https://lgtm.com/projects/g/openMVG/openMVG/rev/pr-a2b0b4c9fdbb0b35d512336ae8aa9a1ed7ef0e8d)

**fixed alerts:**

* 1 for Declaration hides parameter

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pmoulon** [comment]
Thank you @gaoshuai 
Looking forward other pull requests ;-)

**Pull request merged**
