### PR TITLE
[cameras] Add a simple fish-eye distortion model

### PR DESCRIPTION
**Pull request by ORNis**
issue  #423

### CODE REVIEW

**Comment by ORNis** [comment]
For review, not ready to be merged yet

**Comment by pmoulon** [comment]
Tested with success on your image dataset.
I will change change the tab alignment in one file and put eps inside the function.
Having a general eps variable for all the cameras namespace is not a good idea (it can leads to misunderstanding).

**Comment by pmoulon** [comment]
Note: Using a previous calibration of the FishEye lens intrinsic is helping a lot for the GlobalSfM pipeline.

**Comment by pmoulon** [comment]
Merged in the develop_fisheye branch. https://github.com/openMVG/openMVG/commits/develop_fisheye

**Comment by pmoulon** [comment]
:+1:

**Pull request closed without merging**
