### PR TITLE
Add Canon DIGITAL IXUS 70 to sensor DB

### PR DESCRIPTION
**Pull request by john-davies**
Sensor data from here - http://www.dpreview.com/products/canon/compacts/canon_sd1000

### CODE REVIEW

**Comment by pmoulon** [comment]
Thank you. @john-davies 
I will merge it to the develop branch and it will be added to the next coming release.
Don't hesitate to share sparse point cloud reconstruction screenshots of this camera ;-)

**Comment by john-davies** [comment]
Thanks, that's great.

I've started a Github repository -
https://github.com/john-davies/Photogrammetry-examples - to record my more
successful photogrammetry efforts. I've included the original image files
and the sparse and dense reconstructions for reference.

Any feedback is welcome!

Regards
John

**Comment by pmoulon** [comment]
Thanks.
This is a nice door!
I'm sure that playing a bit with the dense reconstruction parameter you will be able to have no more hole in the model.

**Comment by pmoulon** [comment]
Merged in the develop branch https://github.com/openMVG/openMVG/commit/5a3d235d1b970af93cb8c24bddeb9b5199a362ed

**Pull request closed without merging**
