### PR TITLE
modified some places to make it able to compile the software under "ui" folder

### PR DESCRIPTION
**Pull request by chaoer**
1.  modify the "src\software\CMakeList.txt" in line 13-17
    _comment:_
     **change to find Qt5**
      In  " ui\SfM\adjacency_matrix_viewer  ", it uses Qt5.
      In " ui\SfM\control_points_registration ", it uses Qt4.

     In consideration of that we usually use Qt5 now, thus I change this to
     find Qt5.
-------------------------------------------------------------------------------------------------------------------
2.  modify the "src\software\ui\SfM\adjacency_matrix_viewer\matchingpairgraphicsview.h" in line 12
    _comment:_
    **comment the define of class MainFrame**
    When I compile this project (adjacency_matrix_viewer) with Qt5 using
    VS2015 X64, the IDE reports LINK ERROR 2019 unresolved external symbol (
    the construct of class MatchingPairGraphicsView, specifically).

    Thus I uncomment the define of class, and add the include sentence. Then
     the error disappears.

-------------------------------------------------------------------------------------------------------------------
3.  modify the "src\software\ui\SfM\control_points_registration\CMakeLists.txt" 
     _comment:_
      **modify the CMakeList.txt**
       for two reason:
       1. the older one use Qt4;
       2. the older one did not work when I compile it with Qt4.
-------------------------------------------------------------------------------------------------------------------
4.  modify the "src\software\ui\SfM\control_points_registration\mainLayout.hpp" 
                       "src\software\ui\SfM\control_points_registration\mainLayout.cpp" 
                       "src\software\ui\SfM\control_points_registration\GraphicsMainWindow.cpp" 
     _comment:_
     **add includes**
     if without these includes, the IDE (vs2015 x64) reports errors.

### CODE REVIEW

**Comment by chaoer** [comment]
Ok, I got it, 
It seems like the computer which runs the checks do not use Qt5.

**Comment by pmoulon** [comment]
Thanks @chaoer 
Please can you start your dev from the branch called develop?

Master is only used for release:
- We develop new features and improvement and fixes in develop and then merge things in master once the new version is ready.

**Comment by chaoer** [comment]
@pmoulon  Ok.
But I am not sure should I seed this pull request again (after I start from the develop branch ), since it seems like the computer run the check process do not have Qt5.

**Comment by pmoulon** [comment]
@chaoer Any feedback and improvement is welcomed.

I did not catch:
>  the computer run the check process do not have Qt5.

Did you mean your computer or the machine from the continuous integration on Travis?

**Comment by chaoer** [comment]
@pmoulon I mean the machine from the continuous integration on Travis.

**Pull request closed without merging**
