### PR TITLE
interface: openMVG to openMVS

### PR DESCRIPTION
**Pull request by cdcseacave**
thx

### CODE REVIEW

**Comment by pmoulon** [comment]
Thanks @cdcseacave for this PR.
I think that the openMVGtoOpenMVS exporter must be compiled with the same options in order to work.... I mean the _USE_BOOST & _USE_BOOST_SERIALIZATION option must be set to the same value?
Having a transparent handling of the two format would be a nice addition to OpenMVS. Perhaps we could detect the BOOST SERIALIZATION automatically since the file is Zipped... there is certainly a magic header we can check about...

See here the hard coded check https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/Scene.cpp#L65

**Comment by cdcseacave** [comment]
You are right, however the BOOST serialization is there only for historic reasons, it is not and should be never used. In fact I just forgot to delete it, before submitting the PR. I will submit a new PR.

**Comment by pmoulon** [comment]
Thanks for your explaination.
You can update the code in your branch and squash your commits (in order to have only one) and repush to your branch using force, the PR will be automatically updated.

**Comment by cdcseacave** [comment]
sorry, I saw your comment just after I pushed the new commit, hope this works

**Comment by pmoulon** [comment]
Since this binary export a scene without boostless serialization I have some doubt about the behavior in OpenMVG.
I think OpenMVS will not be able to read it; since by default if boost is detected it only read BOOST serialized scene....
I think we should add a _USE_BOOST_SERIALIZATION in order to make program_options still usable, but boost serialization only a compile time option.

**Comment by pmoulon** [comment]
@cdcseacave 
I have tested the interface and it works fine with latest master/develop OpenMVS.
Thanks you!
Perhaps later we will improve the export in order to allow multithreaded image un-distortion...

Hoping that the interface will remains stable from version to version ;-)

**Pull request merged**
